const products = [   
    {
       "name": "Moules de pêche",
       "discount": 5,
       "unit": "kg",
       "id": 6,
       "owner": "tig",
       "sale": true,
       "availability": true,
       "comments": "",
       "category": 1,
       "price": 7
    },   
    {
       "price": 7,
       "comments": "environ 300g",
       "unit": "2 filets",
       "sale": false,
       "availability": true,
       "owner": "tig",
       "category": 0,
       "id": 1,
       "name": "Filet Bar de ligne",
       "discount": 0
    },   
    {
       "discount": 0,
       "owner": "tig",
       "availability": false,
       "price": 7,
       "name": "Araignées",
       "comments": "Hors saison, pêche aux casiers",
       "unit": "kg",
       "sale": false,
       "id": 9,
       "category": 2
    },   
    {
       "id": 10,
       "availability": false,
       "unit": "100g",
       "price": 8,
       "comments": "Hors saison, pêche à l'épuisette",
       "name": "Bouquets cuits",
       "category": 1,
       "sale": false,
       "owner": "tig",
       "discount": 0
    },   
    {
       "unit": "Dz",
       "category": 1,
       "sale": false,
       "owner": "tig",
       "price": 9.5,
       "discount": 0,
       "id": 7,
       "comments": "",
       "availability": true,
       "name": "Huitres N°2 St Vaast"
    },   
    {
       "availability": true,
       "id": 2,
       "unit": "pièce",
       "category": 0,
       "owner": "tig",
       "price": 10,
       "sale": false,
       "name": "Bar de ligne portion",
       "comments": "Environ 550-700g la pièce",
       "discount": 0
    },   
    {
       "sale": false,
       "category": 0,
       "discount": 0,
       "price": 10,
       "comments": "Pêche à la corde",
       "availability": true,
       "name": "Aile de raie",
       "id": 12,
       "unit": "kg",
       "owner": "tig"
    },   
    {
       "unit": "Dz",
       "availability": true,
       "id": 13,
       "price": 12,
       "sale": false,
       "discount": 0,
       "category": 1,
       "name": "Huîtres N°2 OR St Vaast",
       "owner": "tig",
       "comments": "Médaille d'or Salon Agriculture"
    },   
    {
       "owner": "tig",
       "category": 0,
       "name": "Lieu jaune de ligne",
       "sale": false,
       "id": 4,
       "discount": 0,
       "unit": "kg",
       "price": 12,
       "comments": "Environ 550-700g la portion",
       "availability": true
    },   
    {
       "id": 5,
       "comments": "Pêche à la corde",
       "name": "Filet Julienne",
       "availability": false,
       "sale": false,
       "owner": "tig",
       "unit": "kg",
       "category": 0,
       "discount": 0,
       "price": 19
    },   
    {
       "id": 16,
       "category": 1,
       "name": "Huîtres N°2 St Vaast",
       "price": 19,
       "sale": false,
       "discount": 0,
       "comments": "",
       "owner": "tig",
       "unit": "2 Dz",
       "availability": true
    },   
    {
       "id": 14,
       "price": 24,
       "discount": 0,
       "unit": "2 Dz",
       "availability": true,
       "owner": "tig",
       "name": "Huîtres N°2 OR St Vaast",
       "comments": "Médaille d'or salon agriculture",
       "category": 1,
       "sale": false
    },   
    {
       "owner": "tig",
       "name": "Bar de ligne",
       "comments": "Plus de 1.5kg le poisson",
       "discount": 0,
       "availability": true,
       "sale": false,
       "price": 30,
       "category": 0,
       "id": 3,
       "unit": "kg"
    },   
    {
       "owner": "tig",
       "discount": 0,
       "unit": "4 Dz",
       "availability": true,
       "id": 8,
       "comments": "",
       "name": "Huitres N°2 St Vaast",
       "sale": false,
       "category": 1,
       "price": 38
    },   
    {
       "comments": "Médaille d'or salon agriculture",
       "price": 48,
       "unit": "4 Dz",
       "availability": true,
       "sale": false,
       "owner": "tig",
       "id": 15,
       "category": 1,
       "name": "Huîtres N°2 OR St Vaast",
       "discount": 0
    }
 ]

 export default products;